# Generated by Django 2.2.16 on 2020-10-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
