# Generated by Django 2.2.16 on 2020-10-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0002_misionvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderGaleria',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='car')),
                ('texto', models.CharField(max_length=65)),
            ],
        ),
    ]
