# Generated by Django 2.2.16 on 2020-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0003_slidergaleria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=120)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.TextField(max_length=80)),
                ('apellido', models.TextField(max_length=80)),
                ('email', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=80)),
                ('contrasena', models.CharField(max_length=80)),
                ('confirmar', models.CharField(max_length=80)),
            ],
        ),
    ]
