# Generated by Django 2.2.16 on 2020-10-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0004_insumo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='id',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.TextField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
