# Generated by Django 2.2.16 on 2020-10-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0005_auto_20201026_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('imagen', models.ImageField(upload_to='car')),
            ],
        ),
        migrations.DeleteModel(
            name='SliderIndex',
        ),
    ]
