# Generated by Django 2.2.16 on 2020-10-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0006_auto_20201027_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderPhotos',
            new_name='SliderPhoto',
        ),
    ]
