# Generated by Django 2.2.16 on 2020-10-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0007_auto_20201027_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('text', models.TextField(max_length=450)),
                ('image', models.ImageField(upload_to='car')),
            ],
        ),
        migrations.DeleteModel(
            name='MisionVision',
        ),
        migrations.RenameField(
            model_name='sliderphoto',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sliderphoto',
            old_name='nombre',
            new_name='name',
        ),
    ]
