# Generated by Django 2.2.16 on 2020-10-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0008_auto_20201027_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('text', models.TextField(max_length=450)),
                ('image', models.ImageField(upload_to='car')),
            ],
        ),
    ]
