# Generated by Django 2.2.16 on 2020-10-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0010_auto_20201027_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidergalery',
            name='text',
        ),
    ]
