# Generated by Django 2.2.16 on 2020-10-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0011_remove_slidergalery_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderGalery',
            new_name='GaleryPhoto',
        ),
    ]
