# Generated by Django 2.2.16 on 2020-10-27 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0012_auto_20201027_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderphoto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
