# Generated by Django 2.2.16 on 2020-10-28 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0013_sliderphoto_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='insumo',
            old_name='precio',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='insumo',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='id',
            field=models.AutoField(auto_created=True, default='0', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='name',
            field=models.TextField(default='test', max_length=120),
            preserve_default=False,
        ),
    ]
