# Generated by Django 2.2.16 on 2020-10-28 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0014_auto_20201028_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
