# Generated by Django 2.2.16 on 2020-10-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0017_auto_20201028_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
