# Generated by Django 2.2.4 on 2020-11-27 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0019_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContact',
            fields=[
                ('name', models.TextField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='ctype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MisPerritos.TypeContact'),
        ),
    ]
