# Generated by Django 2.2.4 on 2020-11-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0020_auto_20201127_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
