# Generated by Django 2.2.4 on 2020-11-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0021_auto_20201127_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ctype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MisPerritos.TypeContact'),
        ),
    ]
