# Generated by Django 2.2.4 on 2020-11-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0022_auto_20201127_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='typecontact',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
