# Generated by Django 2.2.4 on 2020-11-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerritos', '0023_auto_20201127_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ctype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MisPerritos.TypeContact'),
        ),
    ]
